# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nn-from-scratch',
                'doc_host': 'https://jprzybysz.github.io',
                'git_url': 'https://github.com/jprzybysz/nn-from-scratch',
                'lib_path': 'nn_from_scratch'},
  'syms': {'nn_from_scratch.core': {'nn_from_scratch.core.foo': ('core.html#foo', 'nn_from_scratch/core.py')}}}
